import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminRouter from "./admin";
import programmesRouter from "./programmes";
import parseRouter from "./parse";
import clientsRouter from "./clients";
import wodBrainRouter from "./wod-brain";
import runBrainRouter from "./run-brain";
import strengthBlocksRouter from "./strength-blocks";
import enduranceCyclesRouter from "./endurance-cycles";
import brainRouter from "./brain";
import runSessionsRouter from "./run-sessions";
import engineBuilderRouter from "./engine-builder";
import xlsUploadRouter from "./xls-upload";
import calendarCommandRouter from "./calendar-command";
import sessionLibraryRouter from "./session-library";
import analyticsRouter from "./analytics";
import coachingRouter from "./coaching";
import coachParseRouter from "./coach-parse";
import irlRouter from "./irl";
import teamsRouter from "./teams";
import clientNotesRouter from "./client-notes";
import coachDashboardRouter from "./coach-dashboard";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(programmesRouter);
router.use(parseRouter);
router.use(clientsRouter);
router.use(wodBrainRouter);
router.use(runBrainRouter);
router.use(strengthBlocksRouter);
router.use(enduranceCyclesRouter);
router.use(engineBuilderRouter);
router.use(xlsUploadRouter);
router.use(calendarCommandRouter);
router.use(brainRouter);
router.use(runSessionsRouter);
router.use(sessionLibraryRouter);
router.use(analyticsRouter);
router.use(coachingRouter);
router.use(coachParseRouter);
router.use(irlRouter);
router.use(teamsRouter);
router.use(clientNotesRouter);
router.use(coachDashboardRouter);

export default router;
